### PR TITLE
kat: Cannot find boost library

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
checking for boostlib >= 1.52... yes
checking whether the Boost::Filesystem library is available... yes
configure: WARNING: Could not find a dynamic version of the library!
configure: error: Could not find any version of the library to link to
```

**Comment by philippbayer** [comment]
I had the same problem today and I made a little bit of headway - the manual's `./configure --with-boost=~/.linuxbrew/Cellar/boost/1.60.0_2/` didn't work, but there's a semi-hidden --with-boost-libdir which did the trick for me:
`./configure --with-boost-libdir=/home/pbayer/.linuxbrew/Cellar/boost/1.60.0_2/lib`

```
checking for boostlib >= 1.52... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem-mt... yes
checking for /home/pbayer/.linuxbrew/Cellar/boost/1.60.0_2/lib/libboost_filesystem-mt.a... yes
checking whether the Boost::System library is available... yes
etc.
```

However, `make` doesn't work (yet), crashing with errors like:

```
kat-2.1.1/src/sect.cc:663: undefined reference to boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)
```

The boost-related lines in the Makefile seem to be correctly set so I'm not sure what's happening so far, example:

```
BOOST_CHRONO_STATIC_LIB = /home/pbayer/.linuxbrew/Cellar/boost/1.60.0_2/lib/libboost_chrono-mt.a
```

**Comment by sjackman** [comment]
May or may not be related, but tilde `~` in the middle of a word don't get expanded. Compare and contrast:

``` sh
❯❯❯ echo --with-boost=~/.linuxbrew/Cellar/boost/1.60.0_2/
--with-boost=~/.linuxbrew/Cellar/boost/1.60.0_2/
❯❯❯ echo --with-boost=$HOME/.linuxbrew/Cellar/boost/1.60.0_2/
--with-boost=/home/sjackman/.linuxbrew/Cellar/boost/1.60.0_2/
```

**Comment by philippbayer** [comment]
Ah you're right, so I accidentally used the 'correct' path in `--with-boost-lib`, but not in `--with-boost`! But that still doesn't fix the Makefile, hm

Another note: it explicitly wants python3 and at least on my end expects that the `python`-command starts a python3, so the recipe may want to force the python version in `depends_on`, or during installation set the environment variable `PYTHON` to the path of python3

**Comment by sjackman** [comment]
I got this working using `brew install boost --with-c++11` and your `--with-boost` option to configure.

**Pull request closed without merging**
