### PR TITLE
sambamba: Build a bottle for Linuxbrew: ld: cannot find libphobos2-ldc.a

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Blocked by llvm ldc https://github.com/Linuxbrew/homebrew-core/pull/1027

**Comment by sjackman** [comment]
```
gcc -Wl,--gc-sections -o build/sambamba build/sambamba.o -Lhtslib -Llz4/lib -Wl,-Bstatic -lhts -llz4 -Wl,-Bdynamic -l:libphobos2-ldc.a -l:libdruntime-ldc.a  -lrt -lpthread -lm
/usr/bin/ld: cannot find libphobos2-ldc.a
/usr/bin/ld: cannot find libdruntime-ldc.a
collect2: error: ld returned 1 exit status
make: *** [sambamba-ldmd2-64] Error 1
```
https://travis-ci.org/Linuxbrew/homebrew-science/builds/191145759#L2625
Same error on Circle.

@lomereiter @timotheecour Do you have any insight into this error message from `ldc`?

**Comment by lomereiter** [comment]
@sjackman apparently there's no way to build _both_ shared and static libs in LDC. I use static linking for ease of deployment, as binary compatibility between different versions of phobos/druntime is still unheard of. So it boils down to https://github.com/ldc-developers/ldc/issues/1282 where @timotheecour left a comment already.

**Comment by sjackman** [comment]
Is there an option in `sambamba` to link against the `ldc` dynamic libraries rather than the static ones?

**Comment by lomereiter** [comment]
Well, I could add such an option but then you'd have to maintain a bunch of `libphobos2-nn` packages as it's done on http://d-apt.sourceforge.net/ - which is no fun.
A fix on LDC part is underway, it's easier to just wait for its merge.

**Comment by sjackman** [comment]
@lomereiter @timotheecour It wasn't clear to me that adding `-DBUILD_SHARED_LIBS=ON` to the `ldc` formula also had the effect of disabling static libraries. If static libraries are the default behaviour for `ldc` and formula like `sambamba` depend on that default behaviour, then I'm inclined to revert `ldc` back to static libraries until `ldc` implements having both static and shared libraries. Your thoughts?
See https://github.com/Linuxbrew/homebrew-core/commit/8f0ca08f8388041f4ffa62d3c7a60e608faaf2e0

**Comment by timotheecour** [comment]
Thats recisely why my initial PR containe an option, off by default.

**Comment by timotheecour** [comment]
Another option is to build:
1 bootsrapping ldc
2 static ldc
3 dynamic ldc

Which will be made faster once 2 and 3 can be done in 1 go (pending PR
upstream)

**Comment by sjackman** [comment]
> Thats recisely why my initial PR containe an option, off by default.

That wasn't clear to me from the name of the option. I assumed incorrectly that it built shared libraries in addition to static libraries. I should have asked for clarification. I'm going to revert https://github.com/Linuxbrew/homebrew-core/commit/8f0ca08f8388041f4ffa62d3c7a60e608faaf2e0. See https://github.com/Linuxbrew/homebrew-core/pull/1575

> Which will be made faster once 2 and 3 can be done in 1 go (pending PR
upstream)

I'd prefer to wait for the upstream PR to be merged.

**Comment by sjackman** [comment]
Updated `ldc` and rebuilding `sambamba`.

**Comment by sjackman** [comment]
Success! Merged.

Thanks for updating `ldc`, Timothee. This PR was over a year old.

**Pull request closed without merging**
